### Handle the variables
@address = http://localhost:8080/api

### Obtain all groups
GET {{address}}/groups

### Obtain one group by id
GET {{address}}/groups/1

### Create new group
POST {{address}}/groups
Content-Type: application/json

{
  "name": "Brussels Quarkus Meetup",
  "description": "Quarkus developers in Brussels",
  "city": "Brussels",
  "organizer": "Jane Doe"
}

### Update one group
PUT {{address}}/groups/1
Content-Type: application/json

{
  "name": "Liege Spring Meetup",
  "description": "Spring developers in Liege",
  "city": "Liege",
  "organizer": "Jane Doe",
  "createdAt": "1970-01-01"
}

### Delete one group
DELETE {{address}}/groups/1